### ISSUE TITLE
[Task List] Tasks of hugegraph-ml for GLCC2024

### ISSUE THREAD

**Issue by edw4rdyao** [edw4rdyao/hugegraph-integrate-model-test#4]
### Hugegraph-ml

Hugegraph-ml is a tool that integrates HugeGraph with popular graph learning libraries(like DGL). It implements most graph learning algorithms, enabling users to perform end-to-end graph learning workflows directly from HugeGraph using hugegraph-ml. Graph data can be read directly from HugeGraph and used for tasks such as node embedding, node classification, and graph classification.

- **Simplified flow chart**
  ![image](https://github.com/user-attachments/assets/4d71464c-55a1-457d-a992-acf7bfb01308)
- **Data conversion**
  - [x] Convert single graph from Hugegraph database to DGL graph
  - [ ] Convert multi graphs from Hugegraph database to DGL graphs list
- **Implementation of algorithms and models by DGL**
  - [x] DGI(Deep Graph Infomax) for node embedding
  - [x] GRACE(GRAph Contrastive lEarning) for node embedding
  - [ ] GPR-GNN(Generalized PageRank Graph Neural Network) for node embedding
  - [x] JKNet(Jumping Knowledge Network) for node classification
  - [x] GRAND(Graph RAndom Neural Network) for node classification
  - [ ] DiffPool(Differentiable Pooling) for graph claasification
  - [ ] GIN with Global Pooing for graph claasification
  - [ ] EvolveGCN(Evolving Graph Convolutional Networks) for node classification in dynamic graphs
  - [ ] HAN (Heterogeneous Graph Attention Network) for node classification in heterogeneous graphs
- **Graph learning tasks**
  - [x] Encapsulate node embedding tasks
  - [x] Encapsulate node classification tasks
  - [ ] Encapsulate graph embedding tasks
- **Specific small tasks**
  - [x] Import DGL dataset into Hugegraph database for test
  - [x] Provide early stopping module for graph learning tasks
  - [ ] Allows the user to determine the partitioning of the data set through parameters
  - [ ] Improve training history log
- **Chores**
  - [ ] Add workflow check for hugegraph-ml
